### ISSUE TITLE
Finish RealSphericalHarmonic

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/SphericalHarmonics.jl#8]
@TSGut this would be a good issue to get the hang of things. https://github.com/JuliaApproximation/SphericalHarmonics.jl/pull/6 is a good starting point

**Comment by TSGut** [comment]
Alright. What conventions are we using / do we want? Asking bc I saw bits of your conversation with Mikael in https://github.com/JuliaApproximation/FastTransforms.jl/issues/130 and tests in the transform branch are currently failing on my end due to some (-1)^n inconsistency in the checks.

**Comment by MikaelSlevinsky** [comment]
We could make an `abstract type **Phase end` and have concrete realizations such as `PositiveRealPhase`, `CondonShortleyPhase`, `AlternatingPhase`, `RandomPhase`, ... and then use this to parameterize real and complex spherical harmonic quasi-arrays, and support phase conversions through a canonical phase. I think this would be easier in Julia than in C by multiple dispatch.

**Comment by dlfivefifty** [comment]
I think that already exists as just a lazy multiplication by a diagonal matrix, so no need to make all the different things. Could do const type aliases if there’s really a need

**Comment by dlfivefifty** [comment]
So just use the FastTransforms convention

**Comment by dlfivefifty** [comment]
There’s the question of how to order the coefficients in the block. My vote is to put the m = 0 first

this is nice because one can pull all ` m=0 ` via ` S[:,getindex.(Block.(1:N), 1)] `

**Comment by TSGut** [comment]
It shouldn't be an issue to change this but if m=0 is in first position then what sorting scheme are you proposing for the remaining entries - alternating?

**Comment by dlfivefifty** [comment]
Yes alternating cos and sin. Can give more description when at a computer if you need

**Comment by dlfivefifty** [comment]
` FastTransforms.interlace ` might help you take two vectors and interlace.

**Comment by TSGut** [comment]
The way I have it set up now both the complex and real spherical harmonics code coexist in the same file. Do you want me to separate all the real stuff out into a separate one like it's done in OrthogonalPolynomialsQuasi for different bases or are we okay with the way it is now?

**Comment by dlfivefifty** [comment]
coexisting is probably best since the code is similar
